[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd packages/backend && npm install"]

[phases.build]
cmds = ["cd packages/backend && npm run build"]

[start]
cmd = "cd packages/backend && npm start" 