[phases.setup]
nixPkgs = ["...", "nodejs-18_x"]

[phases.install]
cmds = ["cd packages/frontend && npm install"]

[phases.build]
cmds = ["cd packages/frontend && REACT_APP_API_URL=https://eonmeds-platform2025-production.up.railway.app npm run build"]

[start]
cmd = "cd packages/frontend && npx serve -s build -l $PORT" 