[build]
builder = "NIXPACKS"
buildCommand = "cd packages/backend && npm install && npm run build:full"

[deploy]
startCommand = "cd packages/backend && npm run start:full"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 