[build]
builder = "NIXPACKS"
buildCommand = "cd packages/backend && npm install"
watchPatterns = ["packages/backend/**"]

[deploy]
startCommand = "cd packages/backend && node simple-server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 