[build]
builder = "nixpacks"
buildCommand = "CI=false npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DISABLE_ESLINT_PLUGIN = "true"

[service]
internalPort = 3000 