[build]
builder = "nixpacks"
buildCommand = "CI=true npm ci --include=dev && npm run build:prod"

[deploy]
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300

[service]
internalPort = 3000 