[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DISABLE_ESLINT_PLUGIN = "true"
CI = "false"
TSC_COMPILE_ON_ERROR = "true"
ESLINT_NO_DEV_ERRORS = "true"

[service]
internalPort = 3000 