[build]
builder = "nixpacks"
buildCommand = "npm install --force && CI=true npm run build"

[deploy]
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300

[service]
internalPort = 3000 