[build]
builder = "nixpacks"
buildCommand = "npm install && npm install -g serve && npm run build"

[deploy]
startCommand = "serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DISABLE_ESLINT_PLUGIN = "true"
CI = "false"
TSC_COMPILE_ON_ERROR = "true"
ESLINT_NO_DEV_ERRORS = "true"
REACT_APP_API_URL = "https://eonmeds-platform2025-production.up.railway.app"
REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_live_51RPS5NGzKhM7cZeGlOITW4CImzbMEldvaRbrBQV894nLYUjnSM7rNKTpzeYVZJVOhCbNxmOvOjnR7RN60XdAHvJ100Ksh6ziwy"

[service]
internalPort = 3000 