#!/bin/bash

# Railway Environment Variables Setup Script
# This script outputs the environment variables you need to set in Railway

echo "Copy and paste these environment variables into your Railway dashboard:"
echo ""
echo "# Database Configuration"
echo "DATABASE_URL=postgresql://eonmeds_admin:your_password@eonmeds-dev-db.cxy4o6eyy4sq.us-west-2.rds.amazonaws.com:5432/eonmeds?sslmode=require"
echo "DB_HOST=eonmeds-dev-db.cxy4o6eyy4sq.us-west-2.rds.amazonaws.com"
echo "DB_PORT=5432"
echo "DB_NAME=eonmeds"
echo "DB_USER=eonmeds_admin"
echo "DB_PASSWORD=your_password_here"
echo "DB_SSL=true"
echo ""
echo "# Auth0 Configuration"
echo "AUTH0_DOMAIN=dev-dvouayl22wlz8zwq.us.auth0.com"
echo "AUTH0_AUDIENCE=https://api.eonmeds.com"
echo "AUTH0_CLIENT_ID=L3T6WVUAYDGR5U6sJiKGiLlwU0zJYcjm"
echo "AUTH0_CLIENT_SECRET=your_auth0_client_secret"
echo ""
echo "# JWT Configuration"
echo "JWT_SECRET=your-super-secret-jwt-key-here"
echo ""
echo "# Application Configuration"
echo "NODE_ENV=production"
echo "PORT=3000"
echo ""
echo "# Frontend Variables (for frontend service)"
echo "REACT_APP_API_URL=https://your-backend-service.railway.app"
echo "REACT_APP_AUTH0_DOMAIN=dev-dvouayl22wlz8zwq.us.auth0.com"
echo "REACT_APP_AUTH0_CLIENT_ID=L3T6WVUAYDGR5U6sJiKGiLlwU0zJYcjm"
echo "REACT_APP_AUTH0_REDIRECT_URI=https://your-frontend-service.railway.app/callback"
echo "REACT_APP_AUTH0_AUDIENCE=https://api.eonmeds.com" 