#!/bin/bash
set -euo pipefail

echo "🔐 Auth0 Test User Creation Helper"
echo "=================================="
echo ""
echo "This script will help you create a test user for EONMEDS"
echo ""

# Auth0 Configuration
AUTH0_DOMAIN="dev-dvouayl22wlz8zwq.us.auth0.com"
AUTH0_CLIENT_ID="VPA89aq0Y7N05GvX5KqkDm5JLXPknG0L"

echo "📋 Your Auth0 Configuration:"
echo "   Domain: $AUTH0_DOMAIN"
echo "   Client ID: $AUTH0_CLIENT_ID"
echo ""

echo "📝 To create a test user:"
echo ""
echo "1. Go to: https://manage.auth0.com/"
echo "2. Make sure you're in the '$AUTH0_DOMAIN' tenant"
echo "3. Navigate to: User Management → Users"
echo "4. Click '+ Create User'"
echo "5. Enter these details:"
echo ""
echo "   Email: test@eonmeds.com"
echo "   Password: Test123!@#"
echo "   Connection: Username-Password-Authentication"
echo ""
echo "6. Click 'Create'"
echo ""
echo "📱 Or enable self-registration:"
echo "1. Go to: Authentication → Database"
echo "2. Click on 'Username-Password-Authentication'"
echo "3. Toggle OFF 'Disable Sign Ups'"
echo "4. Users can now register at login page"
echo ""
echo "🌐 Test your login at:"
echo "   • https://d3p4f8m2bxony8.cloudfront.net (HTTPS - Recommended)"
echo "   • http://eonmeds-frontend-staging.s3-website-us-east-1.amazonaws.com (HTTP)"
echo "   • http://localhost:3001 (Local development)"
echo ""
echo "⚠️  IMPORTANT:"
echo "   - S3 websites don't support HTTPS"
echo "   - Use CloudFront URL for secure access"
echo "   - Make sure all URLs are added to Auth0 dashboard"
echo ""
echo "📊 Quick Test Commands:"
echo ""
echo "# Test CloudFront (HTTPS):"
echo "open https://d3p4f8m2bxony8.cloudfront.net"
echo ""
echo "# Test S3 (HTTP only):"
echo "open http://eonmeds-frontend-staging.s3-website-us-east-1.amazonaws.com"
echo ""
echo "# Test Local:"
echo "cd packages/frontend && npm start"
